version: 2
jobs:
  build:
    docker:
      - image: node:7.4.0
    working_directory: ~/TheBrain2.0
    steps:
      - checkout
      - run: mkdir -p ~/TheBrain2.0/artifacts
      - run: ls -la ~/TheBrain2.0/
      - run: pushd ~/TheBrain2.0/server/ ; npm run startTestingDB
      - run: pushd ~/TheBrain2.0/server/ ; npm install
      - run: pushd ~/TheBrain2.0/server/ ; npm test
      - store_artifacts:
          path: ~/TheBrain2.0/artifacts
