version: 2
jobs:
  build:
    docker:
      - image: cypress/base:6
      - image: circleci/mongo:3
    working_directory: ~/TheBrain2.0
    steps:
      - checkout
      - run:
          name: install wait-on
          command: npm install -g wait-on
      - run:
          name: create artifacts folders
          command: |
            mkdir -p ~/TheBrain2.0/server/artifacts
            mkdir -p ~/TheBrain2.0/client/artifacts
            mkdir -p ~/TheBrain2.0/mobileClient/artifacts
#      - run: pushd ~/TheBrain2.0/server/
#      - run: pushd ~/TheBrain2.0/server/ ; npm run startTestingDB
      - restore_cache:
          keys:
            - npm-server-deps-{{ checksum "./server/package.json" }}
      - run:
          name: "install server packages"
          working_directory: "~/TheBrain2.0/server/"
          command: npm install
      - run:
          name: "run server integration/unit tests"
          working_directory: "~/TheBrain2.0/server/"
          command: npm test
          environment: CI=true
      - save_cache:
          key: npm-server-deps-{{ checksum "./server/package.json" }}
          paths:
            - ~/TheBrain2.0/server/node_modules
      - run:
          name: "collect server integration/unit tests coverage"
          working_directory: "~/TheBrain2.0/server/artifacts"
          command: ../node_modules/.bin/codecov -f lcov.info
          environment: CODECOV_TOKEN="c2740296-3f65-4994-beac-37a127192011"
      - run:
          name: "validate standard linting rules on server"
          working_directory: "~/TheBrain2.0/server/"
          command: npm run standard -- > ~/TheBrain2.0/server/artifacts/standardLintingOutput.txt

      - restore_cache:
          keys:
            - npm-client-deps-{{ checksum "./client/package.json"  }}
      - run:
          name: "install web client packages"
          working_directory: "~/TheBrain2.0/client/"
          command: npm install
      - save_cache:
          key: npm-client-deps-{{ checksum "./client/package.json"  }}
          paths:
            - ~/TheBrain2.0/client/node_modules
      - run:
          name: "validate standard linting rules on web client"
          working_directory: "~/TheBrain2.0/client/"
          command: npm run standard -- > ~/TheBrain2.0/client/artifacts/standardLintingOutput.txt

      - restore_cache:
          keys:
            - npm-mobileClient-deps-{{ checksum "./mobileClient/package.json"  }}
      - run:
          name: "install mobile client packages"
          working_directory: "~/TheBrain2.0/mobileClient/"
          command: npm install
      - save_cache:
          key: npm-mobileClient-deps-{{ checksum "./mobileClient/package.json"  }}
          paths:
            - ~/TheBrain2.0/mobileClient/node_modules
      - run: pushd ~/TheBrain2.0/mobileClient/ ; npm run standard -- > ~/TheBrain2.0/mobileClient/artifacts/standardLintingOutput.txt
      - restore_cache:
          keys:
            - npm-testing-deps-{{ checksum "./package.json"  }}
      - run: pushd ~/TheBrain2.0/ ; npm install
      - save_cache:
          key: npm-testing-deps-{{ checksum "./package.json"  }}
          paths:
            - ~/TheBrain2.0/node_modules
      - run: pushd ~/TheBrain2.0/ ; npm run enzymeTest
      - run: pushd ~/TheBrain2.0/ ; npm run enzymeTestMobile
      - run:
          name: start the web client with "stateless" server
          command: pushd ~/TheBrain2.0/client ; npm run startForCypress
          background: true
      - run:
          name: wait for the web client to start up
          command: wait-on "http://localhost:3000" -t 60000
      - run:
          name: Cypress Integration test (without starting up the server)
          command: pushd ~/TheBrain2.0/ ; npm run cypressTestCI
#      - run: pushd ~/TheBrain2.0/ ; npm run cypressTestCI
#      - run: pushd ~/TheBrain2.0/server/artifacts ; COVERALLS_SERVICE_NAME="circle" COVERALLS_REPO_TOKEN="ZWNKI8CkeOa1Fl292BmtSygJaakdxS34Y" COVERALLS_SERVICE_JOB_ID=$CIRCLE_BUILD_NUM cat lcov.info | ../node_modules/.bin/coveralls
      - store_artifacts:
          path: ~/TheBrain2.0/server/artifacts
      - store_artifacts:
          path: ~/TheBrain2.0/client/artifacts
      - store_artifacts:
          path: ~/TheBrain2.0/mobileClient/artifacts
      - store_artifacts:
          path: ~/TheBrain2.0/cypress/videos
