version: 2
jobs:
  build:
    docker:
      - image: node:7.4.0
      - image: circleci/mongo:3
    working_directory: ~/TheBrain2.0
    steps:
      - checkout
      - run: mkdir -p ~/TheBrain2.0/server/artifacts
      - run: ls -la ~/TheBrain2.0/
      - run: pushd ~/TheBrain2.0/server/
#      - run: pushd ~/TheBrain2.0/server/ ; npm run startTestingDB
      - run: npm install
      - run: CI=true npm test
      - store_artifacts:
          path: ~/TheBrain2.0/server/artifacts
